// <auto-generated />
using System;
using DailyPlanService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyPlanService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517103405_PlannedMealCategoryToString")]
    partial class PlannedMealCategoryToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyPlanService.Models.DailyPlan", b =>
                {
                    b.Property<int>("DailyPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DailyPlanId");

                    b.HasIndex("UserId", "TargetDate")
                        .IsUnique();

                    b.ToTable("DailyPlans");
                });

            modelBuilder.Entity("DailyPlanService.Models.PlannedIngredient", b =>
                {
                    b.Property<int>("PlannedIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlannedIngredientId"));

                    b.Property<int>("AmountG")
                        .HasColumnType("int");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlannedMealId")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.HasKey("PlannedIngredientId");

                    b.HasIndex("PlannedMealId");

                    b.ToTable("PlannedMealIngredients");
                });

            modelBuilder.Entity("DailyPlanService.Models.PlannedMeal", b =>
                {
                    b.Property<int>("PlannedMealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlannedMealId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyPlanId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlannedMealId");

                    b.HasIndex("DailyPlanId");

                    b.ToTable("PlannedMeals");
                });

            modelBuilder.Entity("DailyPlanService.Models.PlannedIngredient", b =>
                {
                    b.HasOne("DailyPlanService.Models.PlannedMeal", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyPlanService.Models.PlannedMeal", b =>
                {
                    b.HasOne("DailyPlanService.Models.DailyPlan", null)
                        .WithMany("Meals")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyPlanService.Models.DailyPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("DailyPlanService.Models.PlannedMeal", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
